### ISSUE TITLE
내 프로필 수정  

### ISSUE THREAD

**Issue by eyabc** [eyabc/2019-1-capstone#80]

**Comment by JangHyun11** [comment]
@eyabc
 sql update문 사용하려고하는데
update member
set (email, password, nickname, place) = (value1, value2, value3, value4)
where idx = 1
마리아DB 쿼리에서 실행오류라 어떤식으로 쓰면 좋을지 피드백 부탁해도될까

**Comment by eyabc** [comment]
https://vuejsexamples.com/a-beautiful-vue-component-for-image-cropping-and-uploading/
이미지 업로드

**Comment by eyabc** [comment]
express file upload
서버에 파일 업로드를 하고 데이터베이스에 경로를 저장해야함
